package com.hsy.parrot.config;

public enum ErrorCodeCredit {
    AC_GRAPH_CODE_ERROR, AC_PASSWORD_CONFIRM_DIFF, AC_PASSWORD_OLD_NEW_SAME, AC_PASSWORD_IS_EQUI_DIFFERENT, AC_PASSWORD_LOGIN_FORMAT, AC_PASSWORD_TRADE_FORMAT, AC_PASSWORD_GESTURE_FORMAT, CREDIT_QUERY_BUSINESS_ERROR,
    FTP_FILE_UPLOAD_ERROR,FTP_FILE_READ_ERROR,FTP_FILE_DOWNLOAD_ERROR,FTP_FILE_REMOVE_ERROR,FTP_MOVE_ERROR,FTP_RENAME_ERROR,FTP_LOGIN_ERROR,FTP_FILE_CHECK_ERROR,CO_TEMPLATE_NOT_FOUND
    ,IN_THE_MONITORING_LIST,NO_RISK_INQUIRY,SEE_MORE_SAVE_INFO_ERROR
}
